### ISSUE TITLE
automatic column sizing problems in jupyter and MS Terminal

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/histoprint#18] opened 2020-09-29 14:19 UTC
Hi, first let me say that this package is an amazing utility, that I only had a chance to start playing with now. 

I seem to have an issue both in jupyter and my terminal (MS Terminal) that the histogram doesn't entirely fit into the window width.

![image](https://user-images.githubusercontent.com/13226500/94569775-617a5f80-026e-11eb-8b5f-97f763cd0e62.png)

I found the manual setting, but if the automatic setting worked it would be neat

**Comment by ast0815** [comment] 2020-09-29 14:44
Hmm, seems like it is able to find the right numbre of columns (as indicated by the x-axis tick on the upper right), but those terminals have an issue with the Unicode "magic". Instead of composing the composing characters, they print a second one.

Not sure what could be done about this, except maybe offering a mode with no Unicode composition, but that would remove the forward and backward slashes as possible histogram symbols. 🤔

**Comment by andrzejnovak** [comment] 2020-09-29 15:02
Would it go away, if the histograms were only colors and not symbols?

**Comment by ast0815** [comment] 2020-09-29 15:20
Not at the moment, no. In some fonts, the characters look different when a Unicode composition is added to them. To make everything look consistent, it always adds an "empty" composition character when there is no actual composition happening. That might be another option to "fix" this, only add composing characters when there are actually composing characters in any of the histograms. So when people only use `|`, `=`, and colours, it should work on more terminals.

**Comment by andrzejnovak** [comment] 2020-09-29 19:48
That would be awesome 👍

**Comment by ast0815** [comment] 2020-10-11 11:18
I just checked in Jupyter Lab and there the problem actually seems to be that the autodetection of the terminal width does not work correctly. Not sure I can do anything about that. Just using `columns=40` does work as intended there.

![image](https://user-images.githubusercontent.com/5884065/95677189-b6499e80-0bbb-11eb-8974-56b4bcbb90fa.png)

It does not seem to support colours though.

I'll try to replicate the issue in a proper "dumb" terminal next, to get at the Unicode issue.

**Comment by ast0815** [comment] 2020-10-11 12:34
I made it not use any composing characters if you do not add `/` or `\` to the list of symbols. Since those two are used by default, you need to explicitly set the `symbols` argument when calling `print_hist`. Could you check the devel branch to see if it works for you as expected?

**Comment by andrzejnovak** [comment] 2020-10-11 16:24
Cool it works! Thanks a lot.
![image](https://user-images.githubusercontent.com/13226500/95683810-db570500-0bed-11eb-9ff7-9bf255e2e393.png)

API-wise it's a bit strange that I cannot pass empty string to symbols though `""`  as opposed to `" "`

Wouldn't it also make sense for this to be the default? Why do you need to differentiate the histograms by default both by colour and hatch/char?

Could the symbols used automatically just be adaptive, start with "|=" or whatever renders right in most places and only use the less reliable ones if needed. Perhaps emitting a warning that non-standard symbols will get used and suppress the warning with a kwarg?

**Comment by ast0815** [comment] 2020-10-11 16:40
Well, by default all histograms are plotted on top of one another. If you used only colours, you would not see the first histogram when a second one has a higher bin value as each character can only display one colour. The default set of symbols and colours makes it possible to plot 5 histograms and see them all at the same time. Differentiating by colours alone only works without losing information when you use the `stack` option.

The difference between `symbols = " "` and `symbols = ""` is that in the former case you actually set the symbol to " ", i.e. no symbol. It really is just shorthand for `"     "`, i.e. usually you would provide the symbol for each histogram. When the string of symbols is shorter than the number of histograms, it cycles back over the string as a convenience.

The adaptiveness is a good point. I'll give that a go.

**Comment by ast0815** [comment] 2020-10-11 17:16
I made it so the the combining characters are only used if actually necessary. The default symbols are still the same, but when only 3 or fewer histograms are printed, it does no longer use the combining characters. That should make it "just work" on more terminals at least when printing up to 3 histograms.

I will release a version with these changes and some other fixes later today.

**Closed by ast0815** 2020-10-11 17:16 UTC

**Comment by andrzejnovak** [comment] 2020-10-11 17:42
I think it would be a nice convenience to handle an empty string. _"What symbols should I plot?" "No symbols."_

**Comment by ast0815** [comment] 2020-10-11 18:14
:shrug: Sure why not. The new release is out now.
